services:

  # 🌐 FRONTEND - React con Nginx
  comparendos-frontend:
    container_name: comparendos-frontend
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "60005:80"
    environment:
      - NODE_ENV=production
    volumes:
      # Volumen persistente para node_modules (evita reinstalar)
      - frontend_node_modules:/app/node_modules
      # Volumen para desarrollo (si necesitas hacer cambios)
      - ../../apps/frontend/src:/app/src:ro
    depends_on:
      - comparendos-back
    restart: unless-stopped
    networks:
      - comparendos-network

  # 🌐 FRONTEND DESARROLLO (Opcional - solo para desarrollo)
  comparendos-frontend-dev:
    container_name: comparendos-frontend-dev
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:6002
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Volumen persistente para node_modules
      - frontend_dev_node_modules:/app/node_modules
      # Código fuente para hot reload
      - ../../apps/frontend/src:/app/src
      - ../../apps/frontend/public:/app/public
    depends_on:
      - comparendos-back
    restart: unless-stopped
    networks:
      - comparendos-network
    profiles:
      - development

  # 🚀 BACKEND - Node.js/Express
  comparendos-back:
    container_name: comparendos-back
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile.temp
      args:
        - NODE_ENV=production
    ports:
      - "6002:6002"
    environment:
      - NODE_ENV=production
      - PORT=6002
      - JWT_SECRET=fc013fbc094eb6652c4cb3e7dcd062446ec617c0fe14f11ba20aefa3959cf4f9

    env_file:
      - ./apps/backend/.env
    volumes:
      # Volumen persistente para node_modules del backend
      - backend_node_modules:/app/node_modules
      # Datos de la aplicación
      - /home/administrador/comparendos-data/backend:/app/data
      # Documentación (solo lectura)
      - ../../documentation:/app/documentation:ro
      # Logs persistentes
      - backend_logs:/app/logs
    depends_on:
      - comparendos-db
    restart: unless-stopped
    networks:
      - comparendos-network

  comparendos-db:
    container_name: comparendos-db
    image: postgres:15
    # ⚠️ NO MODIFICAR ESTOS VALORES BAJO NINGÚN CIRCUNSTANCIA
    # Son críticos para el funcionamiento en producción
    environment:
      - POSTGRES_USER=comparendos_user
      - POSTGRES_PASSWORD=comparendos_pass
      - POSTGRES_DB=comparendos_db

    volumes:
      # Volumen persistente para datos de PostgreSQL
      - postgres_data:/var/lib/postgresql/data
      # Scripts de inicialización
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5436:5432"
    restart: unless-stopped
    networks:
      - comparendos-network

networks:
  comparendos-network:
    driver: bridge

volumes:
  # 📦 Volúmenes persistentes para node_modules (evita reinstalar dependencias)
  frontend_node_modules:
    driver: local
  frontend_dev_node_modules:
    driver: local
  backend_node_modules:
    driver: local
  
  # 🗄️ Volúmenes persistentes para datos
  postgres_data:
    driver: local
  backend_logs:
    driver: local
